# Generated by Django 5.2.7 on 2025-11-18 15:40

import django.db.models.deletion
import project.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0011_procurement_current_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时自动填充', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='每次更新时自动填充', verbose_name='更新时间')),
                ('report_code', models.CharField(help_text='周报编号格式: WR2025W01 (WR+年份+W+周数)', max_length=50, primary_key=True, serialize=False, validators=[project.validators.validate_code_field], verbose_name='周报编号')),
                ('year', models.IntegerField(help_text='周报所属年份', verbose_name='年份')),
                ('week', models.IntegerField(help_text='周报所属周数(1-53)', verbose_name='周数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交')], default='draft', help_text='周报状态', max_length=20, verbose_name='状态')),
                ('submit_date', models.DateTimeField(blank=True, help_text='周报提交的时间', null=True, verbose_name='提交时间')),
                ('remarks', models.TextField(blank=True, help_text='周报相关备注信息', verbose_name='备注')),
                ('recorder', models.ForeignKey(help_text='负责填写周报的用户', on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报',
                'ordering': ['-year', '-week'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时自动填充', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='每次更新时自动填充', verbose_name='更新时间')),
                ('progress_code', models.CharField(help_text='进度编号格式: PP2025001', max_length=50, primary_key=True, serialize=False, validators=[project.validators.validate_code_field], verbose_name='进度编号')),
                ('project_name', models.CharField(help_text='采购项目的正式名称', max_length=200, verbose_name='采购项目名称')),
                ('project_code', models.CharField(blank=True, help_text='项目编号(如有)', max_length=50, verbose_name='项目编号')),
                ('current_stage', models.CharField(choices=[('1_planning', '完成采购计划立项'), ('2_requirement', '完成采购需求'), ('3_document', '完成采购文件及规则编制'), ('4_control_price', '完成采购请示及控制价'), ('5_publicity', '完成结果公示'), ('6_contract', '完成采购合同签订'), ('7_archive', '完成采购及采购合同归档')], help_text='采购项目当前所处阶段', max_length=20, verbose_name='当前阶段')),
                ('previous_stage', models.CharField(blank=True, choices=[('1_planning', '完成采购计划立项'), ('2_requirement', '完成采购需求'), ('3_document', '完成采购文件及规则编制'), ('4_control_price', '完成采购请示及控制价'), ('5_publicity', '完成结果公示'), ('6_contract', '完成采购合同签订'), ('7_archive', '完成采购及采购合同归档')], help_text='采购项目上一个阶段', max_length=20, null=True, verbose_name='上一阶段')),
                ('stage_data', models.JSONField(default=dict, help_text='存储各阶段的详细数据(JSON格式)', verbose_name='阶段数据')),
                ('is_archived', models.BooleanField(default=False, help_text='标识该采购项目是否已完成归档', verbose_name='是否已归档')),
                ('archived_date', models.DateTimeField(blank=True, help_text='采购项目归档的时间', null=True, verbose_name='归档时间')),
                ('synced_to_ledger', models.BooleanField(default=False, help_text='标识是否已转入现有台账系统', verbose_name='是否已同步到台账')),
                ('synced_date', models.DateTimeField(blank=True, help_text='同步到台账的时间', null=True, verbose_name='同步时间')),
                ('missing_fields', models.JSONField(default=list, help_text='需要补录的字段列表', verbose_name='缺失字段')),
                ('has_missing_info', models.BooleanField(default=False, help_text='标识是否存在需要补录的信息', verbose_name='存在缺失信息')),
                ('remarks', models.TextField(blank=True, help_text='进度相关备注信息', verbose_name='备注')),
                ('procurement', models.ForeignKey(blank=True, help_text='转入台账后关联的采购记录', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progress_records', to='procurement.procurement', verbose_name='关联采购')),
                ('weekly_report', models.ForeignKey(help_text='该进度记录所属的周报', on_delete=django.db.models.deletion.CASCADE, related_name='progress_items', to='weekly_report.weeklyreport', verbose_name='关联周报')),
            ],
            options={
                'verbose_name': '采购进度',
                'verbose_name_plural': '采购进度',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportReminder',
            fields=[
                ('reminder_code', models.CharField(help_text='提醒编号格式: RMD2025001', max_length=50, primary_key=True, serialize=False, validators=[project.validators.validate_code_field], verbose_name='提醒编号')),
                ('reminder_date', models.DateTimeField(auto_now_add=True, help_text='提醒发送的时间', verbose_name='提醒时间')),
                ('content', models.TextField(help_text='提醒的具体内容', verbose_name='提醒内容')),
                ('reminder_type', models.CharField(default='weekly_report', help_text='提醒类型(weekly_report/missing_info/archive等)', max_length=50, verbose_name='提醒类型')),
                ('is_read', models.BooleanField(default=False, help_text='标识用户是否已读该提醒', verbose_name='是否已读')),
                ('read_date', models.DateTimeField(blank=True, help_text='用户读取提醒的时间', null=True, verbose_name='已读时间')),
                ('is_handled', models.BooleanField(default=False, help_text='标识提醒事项是否已处理', verbose_name='是否已处理')),
                ('handled_date', models.DateTimeField(blank=True, help_text='提醒事项处理的时间', null=True, verbose_name='处理时间')),
                ('related_progress', models.ForeignKey(blank=True, help_text='关联的进度记录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='weekly_report.procurementprogress', verbose_name='关联进度')),
                ('related_report', models.ForeignKey(blank=True, help_text='关联的周报记录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='weekly_report.weeklyreport', verbose_name='关联周报')),
                ('target_user', models.ForeignKey(help_text='接收提醒的用户', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '周报提醒',
                'verbose_name_plural': '周报提醒',
                'ordering': ['-reminder_date'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['report_code'], name='weekly_repo_report__5ca885_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['year', 'week'], name='weekly_repo_year_03f51a_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['recorder', 'status'], name='weekly_repo_recorde_b59fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['submit_date'], name='weekly_repo_submit__e03087_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('year', 'week', 'recorder')},
        ),
        migrations.AddIndex(
            model_name='procurementprogress',
            index=models.Index(fields=['progress_code'], name='weekly_repo_progres_9593bd_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementprogress',
            index=models.Index(fields=['weekly_report', 'current_stage'], name='weekly_repo_weekly__fad3cd_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementprogress',
            index=models.Index(fields=['project_name'], name='weekly_repo_project_99c7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementprogress',
            index=models.Index(fields=['is_archived', 'synced_to_ledger'], name='weekly_repo_is_arch_5c125b_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementprogress',
            index=models.Index(fields=['procurement'], name='weekly_repo_procure_689081_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreportreminder',
            index=models.Index(fields=['reminder_code'], name='weekly_repo_reminde_dff2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreportreminder',
            index=models.Index(fields=['target_user', 'is_read'], name='weekly_repo_target__b8ba56_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreportreminder',
            index=models.Index(fields=['reminder_date'], name='weekly_repo_reminde_b0e351_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreportreminder',
            index=models.Index(fields=['reminder_type'], name='weekly_repo_reminde_5eed61_idx'),
        ),
    ]
