# Generated by Django 5.2.7 on 2025-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementprogress',
            name='missing_fields',
            field=models.JSONField(blank=True, default=list, help_text='需要补录的字段列表', verbose_name='缺失字段'),
        ),
        migrations.AlterField(
            model_name='procurementprogress',
            name='stage_data',
            field=models.JSONField(blank=True, default=dict, help_text='存储各阶段的详细数据(JSON格式)', verbose_name='阶段数据'),
        ),
        migrations.AlterField(
            model_name='weeklyreportreminder',
            name='reminder_type',
            field=models.CharField(choices=[('weekly_report', '周报填写'), ('missing_info', '信息补录'), ('archive', '归档提醒'), ('sync', '同步提醒')], default='weekly_report', help_text='提醒类型', max_length=50, verbose_name='提醒类型'),
        ),
    ]
