# Generated by Django 5.2.7 on 2025-10-20 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时自动设置', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='每次更新时自动更新', verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, help_text='创建该记录的用户', max_length=50, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, help_text='最后更新该记录的用户', max_length=50, verbose_name='更新人')),
                ('contract_code', models.CharField(help_text='例如: HT2025001', max_length=50, primary_key=True, serialize=False, verbose_name='合同编号')),
                ('contract_name', models.CharField(help_text='合同的正式名称', max_length=200, verbose_name='合同名称')),
                ('contract_type', models.CharField(choices=[('主合同', '主合同'), ('补充协议', '补充协议'), ('解除协议', '解除协议')], default='主合同', help_text='区分主合同和补充协议', max_length=20, verbose_name='合同类型')),
                ('contract_source', models.CharField(choices=[('采购合同', '采购合同'), ('直接签订', '直接签订')], default='采购合同', help_text='标识合同是否来源于采购项目', max_length=20, verbose_name='合同来源')),
                ('party_a', models.CharField(blank=True, help_text='合同甲方（通常为我司）', max_length=200, verbose_name='甲方')),
                ('party_b', models.CharField(blank=True, help_text='合同乙方（供应商）', max_length=200, verbose_name='乙方')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, help_text='签订时的合同总价（含税）', max_digits=15, null=True, verbose_name='含税签约合同价(元)')),
                ('signing_date', models.DateField(blank=True, db_index=True, help_text='合同正式签署的日期', null=True, verbose_name='合同签订日期')),
                ('duration', models.CharField(blank=True, help_text='例如: 2025年1月1日至2025年12月31日', max_length=100, verbose_name='合同工期/服务期限')),
                ('contract_officer', models.CharField(blank=True, help_text='负责签订的经办人', max_length=50, verbose_name='合同签订经办人')),
                ('payment_method', models.TextField(blank=True, help_text='例如: 预付30%、完工后验收支付70%', verbose_name='支付方式')),
                ('parent_contract', models.ForeignKey(blank=True, help_text='若为补充协议，则必须关联主合同', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplements', to='contract.contract', verbose_name='关联主合同')),
                ('procurement', models.ForeignKey(blank=True, help_text='当合同来源为"采购合同"时必填；当来源为"直接签订"时可为空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.procurement', verbose_name='关联采购')),
            ],
            options={
                'verbose_name': '合同信息',
                'verbose_name_plural': '合同信息',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract_code'], name='contract_co_contrac_09c9fc_idx'), models.Index(fields=['party_b'], name='contract_co_party_b_c87100_idx'), models.Index(fields=['signing_date'], name='contract_co_signing_1f416c_idx')],
            },
        ),
    ]
