# Generated by Django 5.2.7 on 2025-10-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_sequence',
            field=models.IntegerField(blank=True, help_text='合同的序号，用于排序', null=True, verbose_name='合同序号'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_b_contact',
            field=models.CharField(blank=True, help_text='例如: 李经理 13900139000', max_length=200, verbose_name='乙方负责人及联系方式'),
        ),
        migrations.AddField(
            model_name='contract',
            name='party_b_contact_in_contract',
            field=models.CharField(blank=True, help_text='合同文本中记录的乙方联系方式', max_length=200, verbose_name='合同文本内乙方联系人及方式'),
        ),
        migrations.AddField(
            model_name='contract',
            name='performance_guarantee_return_date',
            field=models.DateField(blank=True, help_text='履约担保退回的日期', null=True, verbose_name='履约担保退回时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='duration',
            field=models.TextField(blank=True, help_text='例如: 2025年1月1日至2025年12月31日', verbose_name='合同工期/服务期限'),
        ),
    ]
