# Generated by Django 5.2.7 on 2025-10-21 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_contract_sequence_contract_party_b_contact_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(blank=True, help_text='该合同所属的项目', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='project.project', verbose_name='关联项目'),
        ),
    ]
