# Generated by Django 5.2.7 on 2025-10-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_sequence',
            field=models.CharField(blank=True, help_text='合同的序号，用于排序和关联（支持字符串格式如 BHHY-NH-001）', max_length=50, null=True, verbose_name='合同序号'),
        ),
    ]
