# Generated by Django 5.2.7 on 2025-10-22 03:49

import project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_contract_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_code',
            field=models.CharField(help_text='合同编号不能包含 / \\ ? # 等URL特殊字符，例如: HT2025001', max_length=50, primary_key=True, serialize=False, validators=[project.validators.validate_code_field], verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_sequence',
            field=models.CharField(blank=True, help_text='合同的序号，不能包含URL特殊字符，支持字符串格式如 BHHY-NH-001', max_length=50, null=True, validators=[project.validators.validate_code_field], verbose_name='合同序号'),
        ),
    ]
