# Generated by Django 5.2.7 on 2025-10-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_contract_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='archive_date',
            field=models.DateField(blank=True, help_text='合同资料归档的日期', null=True, verbose_name='资料归档日期'),
        ),
    ]
