# Generated by Django 5.2.7 on 2025-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_rename_contract_type_to_file_positioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file_positioning',
            field=models.CharField(choices=[('主合同', '主合同'), ('补充协议', '补充协议'), ('解除协议', '解除协议')], default='主合同', help_text='区分主合同、补充协议和解除协议', max_length=20, verbose_name='文件定位'),
        ),
    ]
