# Generated by Django - 添加合同类型字段

from django.db import migrations, models
import project.enums


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_add_qualitative_review_to_bid_evaluation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('工程', '工程'),
                    ('工程货物', '工程货物'),
                    ('工程服务', '工程服务'),
                    ('货物', '货物'),
                    ('服务', '服务')
                ],
                help_text='合同类别(工程/货物/服务等)，可从关联采购或主合同自动继承',
                max_length=100,
                verbose_name='合同类型'
            ),
        ),
    ]