# Generated by Django 5.2.7 on 2025-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_add_contract_type'),
        ('procurement', '0007_add_qualitative_review_to_bid_evaluation_method'),
        ('project', '0003_alter_project_project_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_officer'], name='contract_co_contrac_be9a28_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['archive_date'], name='contract_co_archive_43d584_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['project', 'contract_officer'], name='contract_co_project_6ad7d0_idx'),
        ),
    ]
