# Generated by Django 5.2.7 on 2025-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_contract_contract_co_contrac_be9a28_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建时自动填充', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='每次更新时自动填充', verbose_name='更新时间'),
        ),
    ]
