# Generated by Django 5.2.7 on 2025-11-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_alter_contract_created_at_alter_contract_updated_at'),
        ('weekly_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_from_weekly_report',
            field=models.BooleanField(default=False, help_text='标识该合同记录是否从周报系统转入', verbose_name='来自周报'),
        ),
        migrations.AddField(
            model_name='contract',
            name='related_progress',
            field=models.ForeignKey(blank=True, help_text='关联的周报进度记录', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='weekly_report.procurementprogress', verbose_name='关联进度记录'),
        ),
        migrations.AddField(
            model_name='contract',
            name='weekly_report_sync_date',
            field=models.DateTimeField(blank=True, help_text='从周报系统同步到台账的时间', null=True, verbose_name='周报同步时间'),
        ),
    ]
