# Generated by Django 5.2.7 on 2025-10-20 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时自动设置', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='每次更新时自动更新', verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, help_text='创建该记录的用户', max_length=50, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, help_text='最后更新该记录的用户', max_length=50, verbose_name='更新人')),
                ('payment_code', models.CharField(help_text='例如: HT2025001-FK-001', max_length=50, primary_key=True, serialize=False, verbose_name='付款编号')),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='本次实际支付金额', max_digits=15, verbose_name='实付金额(元)')),
                ('payment_date', models.DateField(db_index=True, help_text='实际支付的日期', verbose_name='付款日期')),
                ('contract', models.ForeignKey(help_text='该笔付款对应的合同', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contract.contract', verbose_name='关联合同')),
            ],
            options={
                'verbose_name': '付款信息',
                'verbose_name_plural': '付款信息',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_code'], name='payment_pay_payment_e36800_idx'), models.Index(fields=['contract'], name='payment_pay_contrac_6e7b38_idx'), models.Index(fields=['payment_date'], name='payment_pay_payment_fe85b9_idx')],
            },
        ),
    ]
