# Generated by Django 5.2.7 on 2025-10-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='标识该笔付款是否已办理结算', verbose_name='是否办理结算'),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='合同的结算价格，如果已办理结算则填写', max_digits=15, null=True, verbose_name='结算价(元)'),
        ),
    ]
