# Generated by Django 5.2.7 on 2025-10-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_is_settled_payment_settlement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, help_text='例如: HT2025001-FK-001，如果为空将自动生成', max_length=50, primary_key=True, serialize=False, verbose_name='付款编号'),
        ),
    ]
