# Generated by Django 5.2.7 on 2025-10-22 03:49

import project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(blank=True, help_text='付款编号不能包含 / \\ ? # 等URL特殊字符，例如: HT2025001-FK-001，如果为空将自动生成', max_length=50, primary_key=True, serialize=False, validators=[project.validators.validate_code_field], verbose_name='付款编号'),
        ),
    ]
