# Generated by Django 5.2.7 on 2025-10-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settlement_archive_date',
            field=models.DateField(blank=True, help_text='结算资料归档的日期', null=True, verbose_name='结算资料归档时间'),
        ),
    ]
