# Generated by Django 5.2.7 on 2025-11-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_contract_contract_co_contrac_be9a28_idx_and_more'),
        ('payment', '0007_alter_foreign_key_to_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(help_text='该笔付款对应的合同', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contract.contract', verbose_name='关联合同'),
        ),
    ]
