# Generated by Django 5.2.7 on 2025-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_payment_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settlement_completion_date',
            field=models.DateField(
                verbose_name='结算完成时间',
                help_text='结算办理完成的日期',
                null=True,
                blank=True,
            ),
        ),
    ]
