# Generated by Django 5.2.7 on 2025-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_add_settlement_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建时自动填充', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='settlement_completion_date',
            field=models.DateField(blank=True, help_text='结算办理完成的日期，格式：YYYY-MM-DD，可选', null=True, verbose_name='结算完成时间'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='每次更新时自动填充', verbose_name='更新时间'),
        ),
    ]
