# Generated by Django 5.2.7 on 2025-10-20 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时自动设置', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='每次更新时自动更新', verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, help_text='创建该记录的用户', max_length=50, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, help_text='最后更新该记录的用户', max_length=50, verbose_name='更新人')),
                ('settlement_code', models.CharField(help_text='例如: JS2025001', max_length=50, primary_key=True, serialize=False, verbose_name='结算编号')),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='主合同+所有补充协议的累计最终结算金额', max_digits=15, verbose_name='最终结算金额(元)')),
                ('completion_date', models.DateField(blank=True, help_text='结算完成的日期', null=True, verbose_name='完成日期')),
                ('remarks', models.TextField(blank=True, help_text='可说明包含哪些补充协议或解除协议的结算情况', verbose_name='结算备注')),
                ('main_contract', models.OneToOneField(help_text='只能关联主合同。主合同+所有补充协议+解除协议共用这一条结算记录', limit_choices_to={'contract_type': '主合同'}, on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='contract.contract', verbose_name='关联主合同')),
            ],
            options={
                'verbose_name': '结算信息',
                'verbose_name_plural': '结算信息',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['settlement_code'], name='settlement__settlem_824d92_idx'), models.Index(fields=['main_contract'], name='settlement__main_co_fdcea1_idx')],
            },
        ),
    ]
