# Generated by Django 5.2.7 on 2025-10-22 03:49

import project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='settlement_code',
            field=models.CharField(help_text='结算编号不能包含 / \\ ? # 等URL特殊字符，例如: JS2025001', max_length=50, primary_key=True, serialize=False, validators=[project.validators.validate_code_field], verbose_name='结算编号'),
        ),
    ]
