# Generated by Django 5.2.7 on 2025-10-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_alter_contract_file_positioning'),
        ('settlement', '0002_alter_settlement_settlement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='main_contract',
            field=models.OneToOneField(help_text='只能关联主合同。主合同+所有补充协议+解除协议共用这一条结算记录', limit_choices_to={'file_positioning': '主合同'}, on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='contract.contract', verbose_name='关联主合同'),
        ),
    ]
