# Generated by Django 5.2.7 on 2025-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_contract_contract_co_contrac_be9a28_idx_and_more'),
        ('settlement', '0003_alter_settlement_main_contract'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['completion_date'], name='settlement__complet_fe2985_idx'),
        ),
    ]
