# Generated by Django 5.2.7 on 2025-10-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(help_text='项目唯一编码，例如: PRJ2025001', max_length=50, primary_key=True, serialize=False, verbose_name='项目编码')),
                ('project_name', models.CharField(help_text='项目的正式名称', max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, help_text='项目的详细描述', verbose_name='项目描述')),
                ('project_manager', models.CharField(blank=True, help_text='负责该项目的人员', max_length=50, verbose_name='项目负责人')),
                ('start_date', models.DateField(blank=True, help_text='项目启动日期', null=True, verbose_name='项目开始日期')),
                ('end_date', models.DateField(blank=True, help_text='项目计划或实际结束日期', null=True, verbose_name='项目结束日期')),
                ('status', models.CharField(choices=[('进行中', '进行中'), ('已完成', '已完成'), ('已暂停', '已暂停'), ('已取消', '已取消')], default='进行中', help_text='项目当前状态', max_length=20, verbose_name='项目状态')),
                ('remarks', models.TextField(blank=True, help_text='项目相关的其他备注信息', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时自动设置', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='每次更新时自动更新', verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, help_text='创建该记录的用户', max_length=50, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, help_text='最后更新该记录的用户', max_length=50, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_code'], name='project_pro_project_2b7797_idx'), models.Index(fields=['project_name'], name='project_pro_project_97e63e_idx'), models.Index(fields=['status'], name='project_pro_status_d7ebb2_idx')],
            },
        ),
    ]
