# Generated by Django 5.2.7 on 2025-10-22 03:49

import project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_created_by_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(help_text='项目编码不能包含 / \\ ? # 等URL特殊字符，例如: PRJ2025001', max_length=50, primary_key=True, serialize=False, validators=[project.validators.validate_code_field], verbose_name='项目编码'),
        ),
    ]
