# Generated by Django 5.2.7 on 2025-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_project_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletenessFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('procurement', '采购'), ('contract', '合同')], help_text='采购或合同', max_length=20, verbose_name='模型类型')),
                ('field_name', models.CharField(help_text='模型中的字段名', max_length=100, verbose_name='字段名称')),
                ('field_label', models.CharField(help_text='字段的中文显示名称', max_length=200, verbose_name='字段标签')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否纳入完整率统计', verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, help_text='显示顺序，数字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '完整率字段配置',
                'verbose_name_plural': '完整率字段配置',
                'ordering': ['model_type', 'sort_order', 'field_name'],
                'indexes': [models.Index(fields=['model_type', 'is_enabled'], name='project_com_model_t_58b37a_idx')],
                'unique_together': {('model_type', 'field_name')},
            },
        ),
    ]
