# Generated by Django 5.2.7 on 2025-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_completenessfieldconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completenessfieldconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建时自动填充', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='completenessfieldconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='每次更新时自动填充', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建时自动填充', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='每次更新时自动填充', verbose_name='更新时间'),
        ),
    ]
