# Generated by Django 5.2.7 on 2025-11-18 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_role_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create', '新增'), ('update', '修改')], help_text='新增或修改', max_length=10, verbose_name='操作类型')),
                ('object_type', models.CharField(choices=[('project', '项目'), ('procurement', '采购'), ('contract', '合同'), ('payment', '付款')], help_text='项目、采购、合同或付款', max_length=20, verbose_name='操作对象类型')),
                ('object_id', models.CharField(help_text='被操作对象的主键', max_length=100, verbose_name='操作对象ID')),
                ('object_repr', models.CharField(blank=True, help_text='对象的字符串表示', max_length=200, verbose_name='对象描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='操作来源IP', null=True, verbose_name='IP地址')),
                ('changes', models.JSONField(blank=True, help_text='修改操作的变更详情(JSON格式)', null=True, verbose_name='变更内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='操作发生的时间', verbose_name='操作时间')),
                ('user', models.ForeignKey(help_text='执行操作的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='project_ope_created_790b54_idx'), models.Index(fields=['user'], name='project_ope_user_id_1b2796_idx'), models.Index(fields=['object_type', 'object_id'], name='project_ope_object__3cda3c_idx')],
            },
        ),
    ]
