# Generated by Django 5.2.7 on 2025-11-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_operationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='description',
            field=models.TextField(blank=True, help_text='详细的操作描述,便于追溯', verbose_name='操作描述'),
        ),
    ]
