# Generated by Django 5.2.7 on 2025-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_operationlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除')], help_text='新增、修改或删除', max_length=10, verbose_name='操作类型'),
        ),
    ]
