# Generated by Django 5.2.7 on 2025-11-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_operationlog_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementMethodFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时自动填充', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='每次更新时自动填充', verbose_name='更新时间')),
                ('method_type', models.CharField(choices=[('strategic_procurement', '战采结果应用'), ('direct_commission', '直接采购'), ('single_source', '单一来源采购'), ('other_methods', '其他采购方式')], help_text='采购方式分类：战采结果应用、直接采购、单一来源采购、其他采购方式', max_length=50, verbose_name='采购方式类型')),
                ('field_name', models.CharField(help_text='采购模型中的字段名', max_length=100, verbose_name='字段名称')),
                ('field_label', models.CharField(help_text='字段的中文显示名称', max_length=200, verbose_name='字段标签')),
                ('is_required', models.BooleanField(default=True, help_text='该字段对此采购方式是否为必填', verbose_name='是否必填')),
                ('sort_order', models.IntegerField(default=0, help_text='显示顺序，数字越小越靠前', verbose_name='排序')),
            ],
            options={
                'verbose_name': '采购方式字段配置',
                'verbose_name_plural': '采购方式字段配置',
                'ordering': ['method_type', 'sort_order', 'field_name'],
                'indexes': [models.Index(fields=['method_type', 'is_required'], name='project_pro_method__24e46d_idx')],
                'unique_together': {('method_type', 'field_name')},
            },
        ),
    ]
