# Generated by Django 5.2.7 on 2025-11-05 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0007_add_qualitative_review_to_bid_evaluation_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImportSession',
            fields=[
                ('session_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pdf_files', models.JSONField(blank=True, default=list, help_text='上传的PDF文件信息列表', verbose_name='PDF文件列表')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='从PDF中提取的字段数据', verbose_name='提取的数据')),
                ('validation_result', models.JSONField(blank=True, default=dict, help_text='数据验证结果和错误信息', verbose_name='验证结果')),
                ('requires_confirmation', models.JSONField(blank=True, default=list, help_text='需要用户确认的字段列表', verbose_name='需确认字段')),
                ('status', models.CharField(choices=[('extracting', '提取中'), ('pending_review', '待确认'), ('confirmed', '已确认'), ('saved', '已保存'), ('expired', '已过期')], db_index=True, default='extracting', max_length=20, verbose_name='状态')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='会话过期时间，过期后自动清理', verbose_name='过期时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_import_sessions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_import_sessions', to='procurement.procurement', verbose_name='关联采购记录')),
            ],
            options={
                'verbose_name': 'PDF导入会话',
                'verbose_name_plural': 'PDF导入会话',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'status'], name='pdf_import__created_4a9fc0_idx'), models.Index(fields=['expires_at'], name='pdf_import__expires_b7ae74_idx'), models.Index(fields=['status', 'created_at'], name='pdf_import__status_c936d3_idx')],
            },
        ),
    ]
