# Generated by Django 5.2.7 on 2025-10-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时自动设置', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='每次更新时自动更新', verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, help_text='创建该记录的用户', max_length=50, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, help_text='最后更新该记录的用户', max_length=50, verbose_name='更新人')),
                ('procurement_code', models.CharField(help_text='例如: GC2025001', max_length=50, primary_key=True, serialize=False, verbose_name='招采编号')),
                ('project_name', models.CharField(help_text='采购项目的正式名称', max_length=200, verbose_name='采购项目名称')),
                ('procurement_unit', models.CharField(blank=True, help_text='发起采购的部门或单位', max_length=200, verbose_name='采购单位')),
                ('winning_unit', models.CharField(blank=True, help_text='最终确定的中标供应商', max_length=200, verbose_name='中标单位')),
                ('winning_contact', models.CharField(blank=True, help_text='例如: 张三 13800138000', max_length=200, verbose_name='中标单位联系人及方式')),
                ('procurement_method', models.CharField(blank=True, help_text='例如: 竞争性谈判、招标、询价等', max_length=50, verbose_name='采购方式')),
                ('procurement_category', models.CharField(blank=True, choices=[('工程', '工程'), ('货物', '货物'), ('服务', '服务')], help_text='采购标的类型', max_length=20, verbose_name='采购类别')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, help_text='项目预算金额', max_digits=15, null=True, verbose_name='采购预算金额(元)')),
                ('control_price', models.DecimalField(blank=True, decimal_places=2, help_text='采购控制价上限', max_digits=15, null=True, verbose_name='采购控制价(元)')),
                ('winning_amount', models.DecimalField(blank=True, decimal_places=2, help_text='最终中标价格', max_digits=15, null=True, verbose_name='中标金额(元)')),
                ('planned_end_date', models.DateField(blank=True, help_text='计划采购完成日期', null=True, verbose_name='计划结束采购时间')),
                ('notice_issue_date', models.DateField(blank=True, help_text='发放中标通知书的日期', null=True, verbose_name='中标通知书发放日期')),
                ('procurement_officer', models.CharField(blank=True, help_text='负责该采购的经办人名称', max_length=50, verbose_name='采购经办人')),
                ('demand_department', models.CharField(blank=True, help_text='需求方部门名称', max_length=100, verbose_name='需求部门')),
            ],
            options={
                'verbose_name': '采购信息',
                'verbose_name_plural': '采购信息',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['procurement_code'], name='procurement_procure_f8e714_idx'), models.Index(fields=['winning_unit'], name='procurement_winning_5b1a94_idx'), models.Index(fields=['created_at'], name='procurement_created_09c837_idx')],
            },
        ),
    ]
