# Generated by Django 5.2.7 on 2025-10-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='procurement',
            name='procurement_winning_5b1a94_idx',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='planned_end_date',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='procurement_category',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='winning_unit',
        ),
        migrations.AddField(
            model_name='procurement',
            name='archive_date',
            field=models.DateField(blank=True, help_text='相关资料归档的日期', null=True, verbose_name='资料归档日期'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='awarding_committee',
            field=models.TextField(blank=True, help_text='定标委员会成员名单，多个成员用逗号分隔', verbose_name='定标委员会成员'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='bid_awarding_method',
            field=models.CharField(blank=True, help_text='例如: 竞争定标法、票决定标法、集体议事法、最低价法、综合评审法', max_length=50, verbose_name='定标方法'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='bid_evaluation_method',
            field=models.CharField(blank=True, help_text='例如: 综合评分法、最低价法', max_length=50, verbose_name='评标方法'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='bid_guarantee',
            field=models.CharField(blank=True, help_text='例如: 银行保函 500000.00 或 保证金 48000.00', max_length=200, verbose_name='投标担保形式及金额（元）'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='bid_guarantee_return_date',
            field=models.DateField(blank=True, help_text='退还投标担保的日期', null=True, verbose_name='中标单位投标担保退回日期'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='bid_opening_date',
            field=models.DateField(blank=True, help_text='开标的日期', null=True, verbose_name='开标日期'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='demand_contact',
            field=models.CharField(blank=True, help_text='例如: 张三 13800138000', max_length=200, verbose_name='需求部门经办人及联系方式'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='evaluation_committee',
            field=models.TextField(blank=True, help_text='评标委员会成员名单，多个成员用逗号分隔', verbose_name='评标委员会成员'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='has_complaint',
            field=models.CharField(blank=True, help_text='例如: 无、有', max_length=50, verbose_name='全程有无投诉'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='non_bidding_explanation',
            field=models.TextField(blank=True, help_text='如果应该招标但未招标，需要说明原因', verbose_name='应招未招说明'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='performance_guarantee',
            field=models.CharField(blank=True, help_text='例如: 银行保函 450000.00', max_length=200, verbose_name='履约担保形式及金额（元）'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='planned_completion_date',
            field=models.DateField(blank=True, help_text='计划采购完成日期', null=True, verbose_name='采购计划完成日期'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='platform_publicity_date',
            field=models.DateField(blank=True, help_text='在阳光采购平台完成公示的日期', null=True, verbose_name='平台中标结果公示完成日期（阳光采购平台）'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='procurement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='招标采购产生的费用', max_digits=15, null=True, verbose_name='招采费用（元）'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='procurement_platform',
            field=models.CharField(blank=True, help_text='例如: 深圳市阳光采购平台', max_length=100, verbose_name='采购平台'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='requirement_approval_date',
            field=models.DateField(blank=True, help_text='OA系统中需求书审批完成的日期', null=True, verbose_name='采购需求书审批完成日期（OA）'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='winning_bidder',
            field=models.CharField(blank=True, help_text='最终确定的中标供应商', max_length=200, verbose_name='中标人'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='项目预算金额', max_digits=15, null=True, verbose_name='预算金额（元）'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='control_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='采购控制价上限', max_digits=15, null=True, verbose_name='采购控制价（元）'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='procurement_officer',
            field=models.CharField(blank=True, help_text='负责该采购的经办人名称', max_length=50, verbose_name='招采经办人'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='project_name',
            field=models.CharField(help_text='采购项目的正式名称', max_length=200, verbose_name='采购名称'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='winning_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='最终中标价格', max_digits=15, null=True, verbose_name='中标价（元）'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='winning_contact',
            field=models.CharField(blank=True, help_text='例如: 李经理 13900139000', max_length=200, verbose_name='中标人联系人及方式'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['winning_bidder'], name='procurement_winning_391f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['bid_opening_date'], name='procurement_bid_ope_654bf4_idx'),
        ),
    ]
