# Generated by Django 5.2.7 on 2025-10-21 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_remove_procurement_procurement_winning_5b1a94_idx_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='project',
            field=models.ForeignKey(blank=True, help_text='该采购所属的项目', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurements', to='project.project', verbose_name='关联项目'),
        ),
    ]
