# Generated by Django 5.2.7 on 2025-10-23 13:06

from django.db import migrations, models


def copy_publicity_dates_forward(apps, schema_editor):
    Procurement = apps.get_model('procurement', 'Procurement')
    for procurement in Procurement.objects.all():
        source_date = getattr(procurement, 'platform_publicity_date', None)
        if source_date and not procurement.result_publicity_release_date:
            procurement.result_publicity_release_date = source_date
            procurement.save(update_fields=['result_publicity_release_date'])


def copy_publicity_dates_backward(apps, schema_editor):
    Procurement = apps.get_model('procurement', 'Procurement')
    for procurement in Procurement.objects.all():
        target_date = procurement.result_publicity_release_date
        if target_date:
            procurement.platform_publicity_date = target_date
            procurement.save(update_fields=['platform_publicity_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_procurement_procurement_code'),
        ('project', '0003_alter_project_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement',
            name='awarding_committee',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='has_complaint',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='procurement_cost',
        ),
        migrations.AddField(
            model_name='procurement',
            name='announcement_release_date',
            field=models.DateField(blank=True, help_text='采购公告在平台发布的日期', null=True, verbose_name='公告发布时间'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='candidate_publicity_end_date',
            field=models.DateField(blank=True, help_text='候选人公示期的结束日期', null=True, verbose_name='候选人公示结束时间'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='candidate_publicity_issue',
            field=models.TextField(blank=True, default='', help_text='记录公示期内质疑的受理与处理情况', verbose_name='候选人公示期质疑情况'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurement',
            name='procurement_category',
            field=models.CharField(blank=True, default='', help_text='采购类别，例如：货物、工程、服务', max_length=100, verbose_name='采购类别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurement',
            name='qualification_review_method',
            field=models.CharField(blank=True, default='', help_text='例如: 资格预审、资格后审', max_length=100, verbose_name='资格审查方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurement',
            name='registration_deadline',
            field=models.DateField(blank=True, help_text='报名截止日期', null=True, verbose_name='报名截止时间'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='result_publicity_release_date',
            field=models.DateField(blank=True, help_text='结果公示发布的日期', null=True, verbose_name='结果公示发布时间'),
        ),
        migrations.RunPython(copy_publicity_dates_forward, copy_publicity_dates_backward),
        migrations.RemoveField(
            model_name='procurement',
            name='platform_publicity_date',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='bid_awarding_method',
            field=models.CharField(blank=True, help_text='例如: 竞争定标法、票决定标法、集体议事法、最低价法、综合评审法', max_length=50, verbose_name='定标方法'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='bid_evaluation_method',
            field=models.CharField(blank=True, help_text='例如: 综合评分法、竞争性谈判、经评审的合理低价法、最低价法', max_length=50, verbose_name='评标谈判方式'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='bid_guarantee_return_date',
            field=models.DateField(blank=True, help_text='退还投标担保的日期', null=True, verbose_name='投标担保退回日期'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='bid_opening_date',
            field=models.DateField(blank=True, help_text='开标的日期', null=True, verbose_name='开标时间'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='项目采购预算金额', max_digits=15, null=True, verbose_name='采购预算金额(元)'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='demand_contact',
            field=models.CharField(blank=True, help_text='例如: 张三 13800138000', max_length=200, verbose_name='申请人联系电话（需求部门）'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='non_bidding_explanation',
            field=models.TextField(blank=True, help_text='如从公开招标调整为单一来源或邀请招标需说明原因', verbose_name='应招未招说明（由公开转单一或邀请的情况）'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='planned_completion_date',
            field=models.DateField(blank=True, help_text='计划采购完成日期', null=True, verbose_name='计划结束采购时间'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='procurement_method',
            field=models.CharField(blank=True, help_text='例如: 公开招标、邀请招标、竞争性谈判等', max_length=50, verbose_name='采购方式'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='procurement_officer',
            field=models.CharField(blank=True, help_text='负责该采购的经办人名称', max_length=50, verbose_name='采购经办人'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='project_name',
            field=models.CharField(help_text='采购项目的正式名称', max_length=200, verbose_name='采购项目名称'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='winning_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='最终中标金额', max_digits=15, null=True, verbose_name='中标金额（元）'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='winning_bidder',
            field=models.CharField(blank=True, help_text='最终确定的中标供应商', max_length=200, verbose_name='中标单位'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='winning_contact',
            field=models.CharField(blank=True, help_text='例如: 李经理 13900139000', max_length=200, verbose_name='中标单位联系人及方式'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['result_publicity_release_date'], name='procurement_result__b9366a_idx'),
        ),
    ]
