# Generated by Django 5.2.7 on 2025-10-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_remove_procurement_awarding_committee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='bid_awarding_method',
            field=models.CharField(blank=True, choices=[('竞争定标法', '竞争定标法'), ('票决定标法', '票决定标法'), ('集体议事法', '集体议事法')], help_text='例如: 票决法、最低价法', max_length=50, verbose_name='定标方法'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='bid_evaluation_method',
            field=models.CharField(blank=True, choices=[('综合评分法', '综合评分法（含综合评估法、综合评审法）'), ('竞争性谈判', '竞争性谈判'), ('价格竞争法', '价格竞争法（含最低价法、经评审的合理低价法）')], help_text='例如: 综合评分法、竞争性谈判', max_length=50, verbose_name='评标谈判方式'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='demand_contact',
            field=models.CharField(blank=True, help_text='需求部门联系人及电话，示例：张三 138****8888', max_length=200, verbose_name='申请人联系电话（需求部门）'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='procurement_category',
            field=models.CharField(blank=True, choices=[('工程', '工程'), ('工程货物', '工程货物'), ('工程服务', '工程服务'), ('货物', '货物'), ('服务', '服务')], help_text='采购类别，可选值：工程, 工程货物, 工程服务, 货物, 服务', max_length=100, verbose_name='采购类别'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='procurement_method',
            field=models.CharField(blank=True, choices=[('公开招标', '公开招标'), ('邀请招标', '邀请招标'), ('公开询价', '公开询价'), ('邀请询价', '邀请询价'), ('公开竞价', '公开竞价'), ('邀请竞价', '邀请竞价'), ('公开比选', '公开比选'), ('邀请比选', '邀请比选'), ('单一来源采购', '单一来源采购'), ('公开竞争性谈判', '公开竞争性谈判'), ('公开竞争性磋商', '公开竞争性磋商'), ('邀请竞争性谈判', '邀请竞争性谈判'), ('邀请竞争性磋商', '邀请竞争性磋商'), ('直接采购', '直接采购'), ('战采结果应用', '战采结果应用')], help_text='采购方式类型，可选：公开招标、邀请招标、公开询价、邀请询价、公开竞价、邀请竞价、公开比选、邀请比选、单一来源采购、公开竞争性谈判、公开竞争性磋商、邀请竞争性谈判、邀请竞争性磋商、直接采购、战采结果应用', max_length=50, verbose_name='采购方式'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='qualification_review_method',
            field=models.CharField(blank=True, choices=[('资格预审', '资格预审'), ('资格后审', '资格后审'), ('投标报名', '投标报名')], help_text='例如: 资格预审、资格后审', max_length=100, verbose_name='资格审查方式'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='winning_contact',
            field=models.CharField(blank=True, help_text='中标供应商联系人及电话，示例：张三 138****8888', max_length=200, verbose_name='中标单位联系人及方式'),
        ),
    ]
