# Generated by Django 5.2.7 on 2025-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_add_qualitative_review_to_bid_evaluation_method'),
        ('project', '0003_alter_project_project_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['procurement_officer'], name='procurement_procure_e6ae30_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['archive_date'], name='procurement_archive_a31638_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['project', 'procurement_officer'], name='procurement_project_bc8987_idx'),
        ),
    ]
