# Generated by Django 5.2.7 on 2025-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_procurement_procurement_procure_e6ae30_idx_and_more'),
        ('project', '0005_alter_completenessfieldconfig_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='记录创建时自动填充', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='每次更新时自动填充', verbose_name='更新时间'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['winning_bidder', 'bid_opening_date'], name='procurement_winning_15091a_idx'),
        ),
        migrations.AddIndex(
            model_name='procurement',
            index=models.Index(fields=['procurement_method', 'budget_amount'], name='procurement_procure_9f7c40_idx'),
        ),
    ]
