# Generated by Django 5.2.7 on 2025-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_alter_procurement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='bid_awarding_method',
            field=models.CharField(blank=True, choices=[('竞争定标法', '竞争定标法'), ('票决定标法', '票决定标法'), ('集体议事法', '集体议事法'), ('上报审批（其他方式采购）', '上报审批（其他方式采购）')], help_text='例如: 票决法、最低价法', max_length=50, verbose_name='定标方法'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='bid_evaluation_method',
            field=models.CharField(blank=True, choices=[('综合评分法', '综合评分法（含综合评估法、综合评审法）'), ('竞争性谈判', '竞争性谈判'), ('价格竞争法', '价格竞争法（含最低价法、经评审的合理低价法）'), ('定性评审法', '定性评审法'), ('其他', '其他')], help_text='例如: 综合评分法、竞争性谈判', max_length=50, verbose_name='评标谈判方式'),
        ),
    ]
