# Generated by Django 5.2.7 on 2025-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_alter_procurement_bid_awarding_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='current_stage',
            field=models.CharField(blank=True, help_text='采购项目当前所处的生命周期阶段(1-7)', max_length=20, verbose_name='当前阶段'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='is_from_weekly_report',
            field=models.BooleanField(default=False, help_text='标识该采购记录是否从周报系统转入', verbose_name='来自周报'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='stage_history',
            field=models.JSONField(blank=True, default=dict, help_text='记录各阶段的进入时间和完成情况', verbose_name='阶段历史'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='weekly_report_sync_date',
            field=models.DateTimeField(blank=True, help_text='从周报系统同步到台账的时间', null=True, verbose_name='周报同步时间'),
        ),
    ]
